// Package docs_api Code generated by swaggo/swag. DO NOT EDIT
package docs_api

import "github.com/swaggo/swag"

const docTemplate = `{
    "schemes": {{ marshal .Schemes }},
    "swagger": "2.0",
    "info": {
        "description": "{{escape .Description}}",
        "title": "{{.Title}}",
        "contact": {},
        "version": "{{.Version}}"
    },
    "host": "{{.Host}}",
    "basePath": "{{.BasePath}}",
    "paths": {
        "/": {
            "get": {
                "description": "An HTML summary of the endpoints this server exposes. Not part of the machine contract — a non-Go backend reimplements /v1/* and nothing more.",
                "produces": [
                    "text/html"
                ],
                "tags": [
                    "ops"
                ],
                "summary": "Server status page",
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "string"
                        }
                    },
                    "503": {
                        "description": "server not installed",
                        "schema": {
                            "type": "string"
                        }
                    }
                }
            }
        },
        "/install": {
            "get": {
                "description": "This implementation's own setup page. It writes the config file, then shows the generated API key exactly once alongside the ed2k:// link that configures eMuleQt in one step. Not part of the machine contract.",
                "consumes": [
                    "application/x-www-form-urlencoded"
                ],
                "produces": [
                    "text/html"
                ],
                "tags": [
                    "install"
                ],
                "summary": "Setup page",
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "string"
                        }
                    },
                    "503": {
                        "description": "the install was refused; nothing was written",
                        "schema": {
                            "type": "string"
                        }
                    }
                }
            }
        },
        "/v1/chunks": {
            "post": {
                "description": "Stores one AES-256-CBC ciphertext blob and returns the absolute URL peers should fetch it from. The URL is the only field a client may use — never rebuild it from the id, since a backend may serve blobs from another host. Content-Length is required; chunked uploads are refused. The server is given no file hash, no part index and no key.",
                "consumes": [
                    "application/octet-stream"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "chunks"
                ],
                "summary": "Store a chunk",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Bearer \u003capiKey\u003e. Optional only when the server has open_upload on.",
                        "name": "Authorization",
                        "in": "header"
                    },
                    {
                        "type": "integer",
                        "description": "Requested lifetime in seconds, clamped to maxTtl",
                        "name": "X-Chunk-TTL",
                        "in": "header"
                    },
                    {
                        "description": "Raw ciphertext",
                        "name": "chunk",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "type": "string"
                        }
                    }
                ],
                "responses": {
                    "201": {
                        "description": "Created",
                        "schema": {
                            "$ref": "#/definitions/http_public.UploadResponse"
                        },
                        "headers": {
                            "Location": {
                                "type": "string",
                                "description": "The same absolute URL as the url field"
                            }
                        }
                    },
                    "400": {
                        "description": "empty body, or a body that ended short of its Content-Length",
                        "schema": {
                            "$ref": "#/definitions/http_public.ErrorResponse"
                        }
                    },
                    "401": {
                        "description": "bad key, or a missing one on a server that requires it",
                        "schema": {
                            "$ref": "#/definitions/http_public.ErrorResponse"
                        }
                    },
                    "411": {
                        "description": "no Content-Length",
                        "schema": {
                            "$ref": "#/definitions/http_public.ErrorResponse"
                        }
                    },
                    "413": {
                        "description": "over maxChunkSize",
                        "schema": {
                            "$ref": "#/definitions/http_public.ErrorResponse"
                        }
                    },
                    "429": {
                        "description": "daily upload quota exhausted",
                        "schema": {
                            "$ref": "#/definitions/http_public.ErrorResponse"
                        }
                    },
                    "503": {
                        "description": "server not installed",
                        "schema": {
                            "$ref": "#/definitions/http_public.ErrorResponse"
                        }
                    },
                    "507": {
                        "description": "storage failure, or free space below min_free_bytes",
                        "schema": {
                            "$ref": "#/definitions/http_public.ErrorResponse"
                        }
                    }
                }
            }
        },
        "/v1/chunks/{id}": {
            "get": {
                "description": "Unauthenticated by design: the 128-bit id is the capability, and the body is ciphertext the server cannot read. Requiring a key here would mean sharing the uploader's credential with every downloader. Single-range requests are answered with a 206; a multi-range request gets the whole entity, which RFC 9110 section 14.2 permits and which is what the eMuleQt downloader can actually parse. HEAD behaves identically without a body.",
                "produces": [
                    "application/octet-stream"
                ],
                "tags": [
                    "chunks"
                ],
                "summary": "Fetch a chunk",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Chunk id, 32 lowercase hex characters",
                        "name": "id",
                        "in": "path",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": "Single byte range, e.g. bytes=0-9728015",
                        "name": "Range",
                        "in": "header"
                    }
                ],
                "responses": {
                    "200": {
                        "description": "the whole ciphertext",
                        "schema": {
                            "type": "string"
                        },
                        "headers": {
                            "ETag": {
                                "type": "string",
                                "description": "First 32 hex characters of the ciphertext digest"
                            },
                            "X-Chunk-Expires": {
                                "type": "string",
                                "description": "Unix time the chunk lapses"
                            }
                        }
                    },
                    "206": {
                        "description": "the requested span",
                        "schema": {
                            "type": "string"
                        },
                        "headers": {
                            "Content-Range": {
                                "type": "string",
                                "description": "bytes \u003cfirst\u003e-\u003clast\u003e/\u003ctotal\u003e"
                            }
                        }
                    },
                    "404": {
                        "description": "unknown, expired, or a malformed id",
                        "schema": {
                            "$ref": "#/definitions/http_public.ErrorResponse"
                        }
                    },
                    "416": {
                        "description": "range not satisfiable",
                        "schema": {
                            "$ref": "#/definitions/http_public.ErrorResponse"
                        }
                    },
                    "503": {
                        "description": "server not installed",
                        "schema": {
                            "$ref": "#/definitions/http_public.ErrorResponse"
                        }
                    }
                }
            },
            "delete": {
                "description": "Only the uploader's key works. A chunk belonging to another key reports 404, not 403, so a valid key cannot be used to probe the id space. Nobody can authenticate as the reserved \"anonymous\" owner, so an open server's chunks are undeletable by design and lapse at their TTL. A 204 guarantees the chunk is gone; a backend that could not remove it says so rather than let the client believe a still-downloadable chunk was deleted.",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "chunks"
                ],
                "summary": "Delete a chunk",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Chunk id, 32 lowercase hex characters",
                        "name": "id",
                        "in": "path",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": "Bearer \u003capiKey\u003e",
                        "name": "Authorization",
                        "in": "header",
                        "required": true
                    }
                ],
                "responses": {
                    "204": {
                        "description": "the chunk is gone"
                    },
                    "401": {
                        "description": "bad or missing API key",
                        "schema": {
                            "$ref": "#/definitions/http_public.ErrorResponse"
                        }
                    },
                    "404": {
                        "description": "unknown, expired, already deleted, or owned by another key",
                        "schema": {
                            "$ref": "#/definitions/http_public.ErrorResponse"
                        }
                    },
                    "500": {
                        "description": "the chunk could not be removed and is still on disk",
                        "schema": {
                            "$ref": "#/definitions/http_public.ErrorResponse"
                        }
                    },
                    "503": {
                        "description": "server not installed",
                        "schema": {
                            "$ref": "#/definitions/http_public.ErrorResponse"
                        }
                    }
                }
            }
        },
        "/v1/info": {
            "get": {
                "description": "Unauthenticated. A client must see \"service\":\"emule-http-cache\" and a version it understands before using the endpoint; this is what stops a configuration link pointing it at an arbitrary host. The probe deliberately carries no credential.",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "ops"
                ],
                "summary": "Server limits and handshake",
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/http_public.InfoResponse"
                        }
                    },
                    "503": {
                        "description": "server not installed",
                        "schema": {
                            "$ref": "#/definitions/http_public.ErrorResponse"
                        }
                    }
                }
            }
        },
        "/v1/stats": {
            "get": {
                "description": "For the operator. Needs an enabled API key, except from a caller on the server itself: a loopback connection carrying no X-Forwarded-For, X-Real-IP or Forwarded header. A request relayed by a reverse proxy always needs the key. An extension of this implementation, not part of the contract — another backend may answer 404. Counters are held in memory and count from startedAt.",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "ops"
                ],
                "summary": "Storage and traffic figures",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Bearer \u003capiKey\u003e. Optional only for a caller on the server itself.",
                        "name": "Authorization",
                        "in": "header"
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/http_public.StatsResponse"
                        }
                    },
                    "401": {
                        "description": "bad or missing API key",
                        "schema": {
                            "$ref": "#/definitions/http_public.ErrorResponse"
                        }
                    },
                    "503": {
                        "description": "server not installed",
                        "schema": {
                            "$ref": "#/definitions/http_public.ErrorResponse"
                        }
                    }
                }
            }
        }
    },
    "definitions": {
        "http_public.ClientStats": {
            "type": "object",
            "properties": {
                "approximate": {
                    "description": "Approximate is always true. The server keeps no addresses; it counts them\nwith HyperLogLog sketches, which are exact for a handful of callers and\nwithin about 1 % beyond that. An IPv6 caller is counted by its /64.",
                    "type": "boolean",
                    "example": true
                },
                "last24h": {
                    "type": "integer",
                    "example": 97
                },
                "total": {
                    "type": "integer",
                    "example": 842
                }
            }
        },
        "http_public.CounterStats": {
            "type": "object",
            "properties": {
                "last24h": {
                    "description": "Last24h is kept in hourly buckets, so it covers the hour in progress and\nthe 24 before it: between 24 and 25 hours.",
                    "type": "integer",
                    "example": 310
                },
                "total": {
                    "description": "Total counts since startedAt.",
                    "type": "integer",
                    "example": 5210
                }
            }
        },
        "http_public.ErrorResponse": {
            "type": "object",
            "properties": {
                "error": {
                    "type": "string",
                    "example": "not found"
                },
                "status": {
                    "type": "integer",
                    "example": 404
                }
            }
        },
        "http_public.InfoResponse": {
            "type": "object",
            "properties": {
                "defaultTtl": {
                    "type": "integer",
                    "example": 172800
                },
                "implementation": {
                    "type": "string",
                    "example": "go"
                },
                "maxChunkSize": {
                    "type": "integer",
                    "example": 10485760
                },
                "maxTtl": {
                    "type": "integer",
                    "example": 604800
                },
                "rangeSupported": {
                    "type": "boolean",
                    "example": true
                },
                "service": {
                    "type": "string",
                    "example": "emule-http-cache"
                },
                "uploadRequiresAuth": {
                    "description": "UploadRequiresAuth is false on a server that takes uploads without a\ncredential. It is never a reason for a client to drop the key it has — a\nkey is still what authorises DELETE, and the operator may close the\nserver again tomorrow.",
                    "type": "boolean",
                    "example": true
                },
                "version": {
                    "type": "integer",
                    "example": 1
                }
            }
        },
        "http_public.RejectedStats": {
            "type": "object",
            "properties": {
                "notFound": {
                    "$ref": "#/definitions/http_public.CounterStats"
                },
                "quotaExceeded": {
                    "$ref": "#/definitions/http_public.CounterStats"
                },
                "storageFull": {
                    "$ref": "#/definitions/http_public.CounterStats"
                },
                "tooLarge": {
                    "$ref": "#/definitions/http_public.CounterStats"
                },
                "unauthorized": {
                    "$ref": "#/definitions/http_public.CounterStats"
                }
            }
        },
        "http_public.StatsResponse": {
            "type": "object",
            "properties": {
                "clients": {
                    "$ref": "#/definitions/http_public.ClientStats"
                },
                "startedAt": {
                    "description": "StartedAt is when this process started, in unix seconds. Every \"total\"\nbelow counts from here: the counters live in memory and a restart zeroes\nthem.",
                    "type": "integer",
                    "example": 1791283200
                },
                "storage": {
                    "$ref": "#/definitions/http_public.StorageStats"
                },
                "traffic": {
                    "$ref": "#/definitions/http_public.TrafficStats"
                }
            }
        },
        "http_public.StorageStats": {
            "type": "object",
            "properties": {
                "asOf": {
                    "description": "AsOf is when the store was last walked, in unix seconds. The figures are\nreused for a few seconds.",
                    "type": "integer",
                    "example": 1791369600
                },
                "bytes": {
                    "type": "integer",
                    "example": 11712531264
                },
                "chunks": {
                    "description": "Chunks and Bytes cover every chunk present, expired or not.",
                    "type": "integer",
                    "example": 1204
                },
                "expiredBytes": {
                    "type": "integer",
                    "example": 359936592
                },
                "expiredChunks": {
                    "description": "ExpiredChunks and ExpiredBytes are the part of the above that is past its\nTTL and waiting for the next sweep.",
                    "type": "integer",
                    "example": 37
                }
            }
        },
        "http_public.TrafficStats": {
            "type": "object",
            "properties": {
                "deletes": {
                    "$ref": "#/definitions/http_public.CounterStats"
                },
                "downloadedBytes": {
                    "$ref": "#/definitions/http_public.CounterStats"
                },
                "downloads": {
                    "description": "Downloads counts GET responses that carried chunk bytes, whole or a\nRange. DownloadedBytes is what was actually sent, so an interrupted\ntransfer counts for as far as it got.",
                    "allOf": [
                        {
                            "$ref": "#/definitions/http_public.CounterStats"
                        }
                    ]
                },
                "gcExpired": {
                    "description": "GCExpired counts chunks reclaimed by this process's own sweeper. A ` + "`" + `gc` + "`" + `\nrun from cron is another process and is not seen here.",
                    "allOf": [
                        {
                            "$ref": "#/definitions/http_public.CounterStats"
                        }
                    ]
                },
                "rejected": {
                    "$ref": "#/definitions/http_public.RejectedStats"
                },
                "uploadedBytes": {
                    "$ref": "#/definitions/http_public.CounterStats"
                },
                "uploads": {
                    "$ref": "#/definitions/http_public.CounterStats"
                }
            }
        },
        "http_public.UploadResponse": {
            "type": "object",
            "properties": {
                "expires": {
                    "type": "integer",
                    "example": 1755500000
                },
                "id": {
                    "type": "string",
                    "example": "87d7f7573b0263fc9faf9ed65cb62841"
                },
                "sha256": {
                    "type": "string",
                    "example": "e3b0c44298fc1c149afbf4c8996fb92427ae41e4649b934ca495991b7852b855"
                },
                "size": {
                    "type": "integer",
                    "example": 9728016
                },
                "url": {
                    "type": "string",
                    "example": "http://localhost:8080/v1/chunks/87d7f7573b0263fc9faf9ed65cb62841"
                }
            }
        }
    }
}`

// SwaggerInfo holds exported Swagger Info so clients can modify it
var SwaggerInfo = &swag.Spec{
	Version:          "1.0",
	Host:             "",
	BasePath:         "/",
	Schemes:          []string{},
	Title:            "emule-http-cache API",
	Description:      "Encrypted chunk cache for eMuleQt's HTTP Cache feature.\nAn uploader stores one AES-256-CBC blob here and hands its URL to several peers, so a part is uploaded once and fetched many times. The server holds ciphertext it has no key for, and is never told the file hash or the part number. Chunk downloads are unauthenticated by design: the 128-bit chunk id is the capability.",
	InfoInstanceName: "swagger",
	SwaggerTemplate:  docTemplate,
	LeftDelim:        "{{",
	RightDelim:       "}}",
}

func init() {
	swag.Register(SwaggerInfo.InstanceName(), SwaggerInfo)
}
